name: Get Widget Versions
on:
  workflow_call:
    outputs:
      widget-backgroundcolour-branch:
        description: Branch name of background colour widget
        value: ${{ jobs.widget-versions.outputs.widget-backgroundcolour-branch }}
      widget-fontface-branch:
        description: Branch name of font face widget
        value: ${{ jobs.widget-versions.outputs.widget-fontface-branch }}
      widget-fontkerning-branch:
        description: Branch name of font kerning widget
        value: ${{ jobs.widget-versions.outputs.widget-fontkerning-branch }}
      widget-fontsize-branch:
        description: Branch name of font size widget
        value: ${{ jobs.widget-versions.outputs.widget-fontsize-branch }}
      widget-imagevisibility-branch:
        description: Branch name of image visibility widget
        value: ${{ jobs.widget-versions.outputs.widget-imagevisibility-branch }}
      widget-letterspacing-branch:
        description: Branch name of letter spacing widget
        value: ${{ jobs.widget-versions.outputs.widget-letterspacing-branch }}
      widget-lineheight-branch:
        description: Branch name of line height widget
        value: ${{ jobs.widget-versions.outputs.widget-lineheight-branch }}
      widget-linkhighlight-branch:
        description: Branch name of link highlight widget
        value: ${{ jobs.widget-versions.outputs.widget-linkhighlight-branch }}
      widget-textcolour-branch:
        description: Branch name of text colour widget
        value: ${{ jobs.widget-versions.outputs.widget-textcolour-branch }}
jobs:
  widget-versions:
    name: Get default widget versions
    runs-on: ubuntu-latest
    outputs:
      widget-backgroundcolour-branch: ${{ steps.widget-branches.outputs.WIDGET_BACKGROUNDCOLOUR_VERSION }}
      widget-fontface-branch: ${{ steps.widget-branches.outputs.WIDGET_FONTFACE_VERSION }}
      widget-fontkerning-branch: ${{ steps.widget-branches.outputs.WIDGET_FONTKERNING_VERSION }}
      widget-fontsize-branch: ${{ steps.widget-branches.outputs.WIDGET_FONTSIZE_VERSION }}
      widget-imagevisibility-branch: ${{ steps.widget-branches.outputs.WIDGET_IMAGEVISIBILITY_VERSION }}
      widget-letterspacing-branch: ${{ steps.widget-branches.outputs.WIDGET_LETTERSPACING_VERSION }}
      widget-lineheight-branch: ${{ steps.widget-branches.outputs.WIDGET_LINEHEIGHT_VERSION }}
      widget-linkhighlight-branch: ${{ steps.widget-branches.outputs.WIDGET_LINKHIGHLIGHT_VERSION }}
      widget-textcolour-branch: ${{ steps.widget-branches.outputs.WIDGET_TEXTCOLOUR_VERSION }}
    steps:
      - name: Get widget version
        id: get-widget-versions
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo WIDGET_BACKGROUNDCOLOUR_VERSION_JSON=$(gh release view --json name -R ponlawat-w/moodle-accessibility_backgroundcolour || echo '{"name":"release"}') >> $GITHUB_OUTPUT
          echo WIDGET_FONTFACE_VERSION_JSON=$(gh release view --json name -R ponlawat-w/moodle-accessibility_fontface || echo '{"name":"release"}') >> $GITHUB_OUTPUT
          echo WIDGET_FONTKERNING_VERSION_JSON=$(gh release view --json name -R ponlawat-w/moodle-accessibility_fontkerning || echo '{"name":"release"}') >> $GITHUB_OUTPUT
          echo WIDGET_FONTSIZE_VERSION_JSON=$(gh release view --json name -R ponlawat-w/moodle-accessibility_fontsize || echo '{"name":"release"}') >> $GITHUB_OUTPUT
          echo WIDGET_IMAGEVISIBILITY_VERSION_JSON=$(gh release view --json name -R ponlawat-w/moodle-accessibility_imagevisibility || echo '{"name":"release"}') >> $GITHUB_OUTPUT
          echo WIDGET_LETTERSPACING_VERSION_JSON=$(gh release view --json name -R ponlawat-w/moodle-accessibility_letterspacing || echo '{"name":"release"}') >> $GITHUB_OUTPUT
          echo WIDGET_LINEHEIGHT_VERSION_JSON=$(gh release view --json name -R ponlawat-w/moodle-accessibility_lineheight || echo '{"name":"release"}') >> $GITHUB_OUTPUT
          echo WIDGET_LINKHIGHLIGHT_VERSION_JSON=$(gh release view --json name -R ponlawat-w/moodle-accessibility_linkhighlight || echo '{"name":"release"}') >> $GITHUB_OUTPUT
          echo WIDGET_TEXTCOLOUR_VERSION_JSON=$(gh release view --json name -R ponlawat-w/moodle-accessibility_textcolour || echo '{"name":"release"}') >> $GITHUB_OUTPUT
      - name: Get widget branch names
        id: widget-branches
        run: |
          echo "WIDGET_BACKGROUNDCOLOUR_VERSION=${{ fromJson(steps.get-widget-versions.outputs.WIDGET_BACKGROUNDCOLOUR_VERSION_JSON).name }}" >> $GITHUB_OUTPUT
          echo "WIDGET_FONTFACE_VERSION=${{ fromJson(steps.get-widget-versions.outputs.WIDGET_FONTFACE_VERSION_JSON).name }}" >> $GITHUB_OUTPUT
          echo "WIDGET_FONTKERNING_VERSION=${{ fromJson(steps.get-widget-versions.outputs.WIDGET_FONTKERNING_VERSION_JSON).name }}" >> $GITHUB_OUTPUT
          echo "WIDGET_FONTSIZE_VERSION=${{ fromJson(steps.get-widget-versions.outputs.WIDGET_FONTSIZE_VERSION_JSON).name }}" >> $GITHUB_OUTPUT
          echo "WIDGET_IMAGEVISIBILITY_VERSION=${{ fromJson(steps.get-widget-versions.outputs.WIDGET_IMAGEVISIBILITY_VERSION_JSON).name }}" >> $GITHUB_OUTPUT
          echo "WIDGET_LETTERSPACING_VERSION=${{ fromJson(steps.get-widget-versions.outputs.WIDGET_LETTERSPACING_VERSION_JSON).name }}" >> $GITHUB_OUTPUT
          echo "WIDGET_LINEHEIGHT_VERSION=${{ fromJson(steps.get-widget-versions.outputs.WIDGET_LINEHEIGHT_VERSION_JSON).name }}" >> $GITHUB_OUTPUT
          echo "WIDGET_LINKHIGHLIGHT_VERSION=${{ fromJson(steps.get-widget-versions.outputs.WIDGET_LINKHIGHLIGHT_VERSION_JSON).name }}" >> $GITHUB_OUTPUT
          echo "WIDGET_TEXTCOLOUR_VERSION=${{ fromJson(steps.get-widget-versions.outputs.WIDGET_TEXTCOLOUR_VERSION_JSON).name }}" >> $GITHUB_OUTPUT
